# frozen_string_literal: true

source 'https://rubygems.org'
gem 'ffi'
gem 'puma'
gem 'rack'
gem 'sinatra', github: 'sinatra/sinatra'

# other dependencies
gem 'erb'
group :test do
  gem 'rack-test'
  gem 'rspec'
end

group :development, :test do
  gem 'rerun'
end
