source 'https://rubygems.org'
gem 'sinatra', :github => 'sinatra/sinatra'
gem 'puma'
gem 'rack'
gem 'ffi'

# other dependencies
gem 'erb'
group :test do
  gem 'rack-test'
  gem 'rspec'
end

group :development, :test do
  gem "rerun"
end
